# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name_of_service',
            new_name='name',
        ),
    ]
