# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190305_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
